import type {Metadata} from 'next';
import {Inter} from 'next/font/google';

import ProvidersLayout from './(providers)/layout';
import './globals.css';
import Header from './(providers)/(root)/_components/Header';
import MainWrapper from './(providers)/(root)/_components/MainWrapper';
import Footer from './(providers)/(root)/_components/Footer';
import React from 'react';

const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
  title: 'WhatSurv?',
  description: 'Generated by create next app',
};

export type HTMLLayoutProps = {
  children: React.ReactNode;
};

export default function HTMLLayout({children}: HTMLLayoutProps) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ProvidersLayout>
          <Header />
          <MainWrapper>{children}</MainWrapper>
          <Footer />
        </ProvidersLayout>
      </body>
    </html>
  );
}
